// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (
    tenant_id,
    name,
    key_prefix,
    key_hash,
    scopes,
    type,
    status,
    expires_at,
    created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, tenant_id, name, key_prefix, key_hash, scopes, type, status, expires_at, last_used_at, created_by, created_at, revoked_at, revoked_by
`

type CreateAPIKeyParams struct {
	TenantID  uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	Name      string             `db:"name" json:"name"`
	KeyPrefix string             `db:"key_prefix" json:"key_prefix"`
	KeyHash   string             `db:"key_hash" json:"key_hash"`
	Scopes    []string           `db:"scopes" json:"scopes"`
	Type      string             `db:"type" json:"type"`
	Status    string             `db:"status" json:"status"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedBy uuid.UUID          `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.TenantID,
		arg.Name,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.Scopes,
		arg.Type,
		arg.Status,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Scopes,
		&i.Type,
		&i.Status,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.RevokedBy,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys
WHERE id = $1 AND tenant_id = $2
`

type DeleteAPIKeyParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) error {
	_, err := q.db.Exec(ctx, deleteAPIKey, arg.ID, arg.TenantID)
	return err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, tenant_id, name, key_prefix, key_hash, scopes, type, status, expires_at, last_used_at, created_by, created_at, revoked_at, revoked_by FROM api_keys
WHERE key_hash = $1
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Scopes,
		&i.Type,
		&i.Status,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.RevokedBy,
	)
	return i, err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT id, tenant_id, name, key_prefix, key_hash, scopes, type, status, expires_at, last_used_at, created_by, created_at, revoked_at, revoked_by FROM api_keys
WHERE id = $1 AND tenant_id = $2
`

type GetAPIKeyByIDParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) GetAPIKeyByID(ctx context.Context, arg GetAPIKeyByIDParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByID, arg.ID, arg.TenantID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Scopes,
		&i.Type,
		&i.Status,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.RevokedBy,
	)
	return i, err
}

const listAPIKeysByTenant = `-- name: ListAPIKeysByTenant :many
SELECT id, tenant_id, name, key_prefix, key_hash, scopes, type, status, expires_at, last_used_at, created_by, created_at, revoked_at, revoked_by FROM api_keys
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByTenant(ctx context.Context, tenantID uuid.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.KeyPrefix,
			&i.KeyHash,
			&i.Scopes,
			&i.Type,
			&i.Status,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.RevokedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :one
UPDATE api_keys
SET status = 'revoked',
    revoked_at = NOW(),
    revoked_by = $2
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, name, key_prefix, key_hash, scopes, type, status, expires_at, last_used_at, created_by, created_at, revoked_at, revoked_by
`

type RevokeAPIKeyParams struct {
	ID        uuid.UUID   `db:"id" json:"id"`
	RevokedBy pgtype.UUID `db:"revoked_by" json:"revoked_by"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, revokeAPIKey, arg.ID, arg.RevokedBy)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Scopes,
		&i.Type,
		&i.Status,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.RevokedBy,
	)
	return i, err
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :one
UPDATE api_keys
SET last_used_at = NOW()
WHERE id = $1
RETURNING id, tenant_id, name, key_prefix, key_hash, scopes, type, status, expires_at, last_used_at, created_by, created_at, revoked_at, revoked_by
`

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, id uuid.UUID) (ApiKey, error) {
	row := q.db.QueryRow(ctx, updateAPIKeyLastUsed, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Scopes,
		&i.Type,
		&i.Status,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.RevokedBy,
	)
	return i, err
}
