// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_logs.sql

package sqlcgen

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT COUNT(*) FROM audit_logs
WHERE (tenant_id = $1 OR $1::uuid IS NULL)
  AND (actor_id = $2 OR $2::uuid IS NULL)
  AND (event = $3 OR $3::audit_event_type IS NULL)
`

type CountAuditLogsParams struct {
	TenantID pgtype.UUID     `db:"tenant_id" json:"tenant_id"`
	ActorID  pgtype.UUID     `db:"actor_id" json:"actor_id"`
	Event    *AuditEventType `db:"event" json:"event"`
}

func (q *Queries) CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs, arg.TenantID, arg.ActorID, arg.Event)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (tenant_id, actor_id, target_id, event, ip_address, user_agent, metadata)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5::inet,
  $6,
  $7
)
`

type CreateAuditLogParams struct {
	TenantID  pgtype.UUID    `db:"tenant_id" json:"tenant_id"`
	ActorID   pgtype.UUID    `db:"actor_id" json:"actor_id"`
	TargetID  pgtype.UUID    `db:"target_id" json:"target_id"`
	Event     AuditEventType `db:"event" json:"event"`
	IpAddress *netip.Addr    `db:"ip_address" json:"ip_address"`
	UserAgent *string        `db:"user_agent" json:"user_agent"`
	Metadata  []byte         `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.TenantID,
		arg.ActorID,
		arg.TargetID,
		arg.Event,
		arg.IpAddress,
		arg.UserAgent,
		arg.Metadata,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, tenant_id, actor_id, target_id, event, ip_address, user_agent, metadata, created_at FROM audit_logs
WHERE (tenant_id = $3 OR $3::uuid IS NULL)
  AND (actor_id = $4 OR $4::uuid IS NULL)
  AND (event = $5 OR $5::audit_event_type IS NULL)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAuditLogsParams struct {
	Limit    int32           `db:"limit" json:"limit"`
	Offset   int32           `db:"offset" json:"offset"`
	TenantID pgtype.UUID     `db:"tenant_id" json:"tenant_id"`
	ActorID  pgtype.UUID     `db:"actor_id" json:"actor_id"`
	Event    *AuditEventType `db:"event" json:"event"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.Limit,
		arg.Offset,
		arg.TenantID,
		arg.ActorID,
		arg.Event,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ActorID,
			&i.TargetID,
			&i.Event,
			&i.IpAddress,
			&i.UserAgent,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
