// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity_tokens.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createIdentityToken = `-- name: CreateIdentityToken :one
INSERT INTO identity_tokens (user_id, type, hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, type, hash, expires_at, used_at, created_at
`

type CreateIdentityTokenParams struct {
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	Type      TokenType `db:"type" json:"type"`
	Hash      string    `db:"hash" json:"hash"`
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateIdentityToken(ctx context.Context, arg CreateIdentityTokenParams) (IdentityToken, error) {
	row := q.db.QueryRow(ctx, createIdentityToken,
		arg.UserID,
		arg.Type,
		arg.Hash,
		arg.ExpiresAt,
	)
	var i IdentityToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Hash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredIdentityTokens = `-- name: DeleteExpiredIdentityTokens :execrows
DELETE FROM identity_tokens
WHERE expires_at < NOW() OR used_at IS NOT NULL
`

func (q *Queries) DeleteExpiredIdentityTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdentityTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdentityTokenByHash = `-- name: GetIdentityTokenByHash :one
SELECT id, user_id, type, hash, expires_at, used_at, created_at FROM identity_tokens
WHERE hash = $1
  AND used_at IS NULL
  AND expires_at > NOW()
`

func (q *Queries) GetIdentityTokenByHash(ctx context.Context, hash string) (IdentityToken, error) {
	row := q.db.QueryRow(ctx, getIdentityTokenByHash, hash)
	var i IdentityToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Hash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const invalidateUserTokensByType = `-- name: InvalidateUserTokensByType :exec
UPDATE identity_tokens SET used_at = NOW()
WHERE user_id = $1 AND type = $2 AND used_at IS NULL
`

type InvalidateUserTokensByTypeParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	Type   TokenType `db:"type" json:"type"`
}

func (q *Queries) InvalidateUserTokensByType(ctx context.Context, arg InvalidateUserTokensByTypeParams) error {
	_, err := q.db.Exec(ctx, invalidateUserTokensByType, arg.UserID, arg.Type)
	return err
}

const markIdentityTokenUsed = `-- name: MarkIdentityTokenUsed :exec
UPDATE identity_tokens SET used_at = NOW() WHERE id = $1
`

func (q *Queries) MarkIdentityTokenUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markIdentityTokenUsed, id)
	return err
}
