// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity_providers.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createExternalAccount = `-- name: CreateExternalAccount :one
INSERT INTO external_accounts (id, user_id, provider_id, external_id, email, name, avatar_url, access_token, refresh_token, token_expiry, raw_data)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, user_id, provider_id, external_id, email, name, avatar_url, access_token, refresh_token, token_expiry, raw_data, created_at, updated_at
`

type CreateExternalAccountParams struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	UserID       uuid.UUID          `db:"user_id" json:"user_id"`
	ProviderID   uuid.UUID          `db:"provider_id" json:"provider_id"`
	ExternalID   string             `db:"external_id" json:"external_id"`
	Email        *string            `db:"email" json:"email"`
	Name         *string            `db:"name" json:"name"`
	AvatarUrl    *string            `db:"avatar_url" json:"avatar_url"`
	AccessToken  *string            `db:"access_token" json:"access_token"`
	RefreshToken *string            `db:"refresh_token" json:"refresh_token"`
	TokenExpiry  pgtype.Timestamptz `db:"token_expiry" json:"token_expiry"`
	RawData      []byte             `db:"raw_data" json:"raw_data"`
}

func (q *Queries) CreateExternalAccount(ctx context.Context, arg CreateExternalAccountParams) (ExternalAccount, error) {
	row := q.db.QueryRow(ctx, createExternalAccount,
		arg.ID,
		arg.UserID,
		arg.ProviderID,
		arg.ExternalID,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiry,
		arg.RawData,
	)
	var i ExternalAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProviderID,
		&i.ExternalID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiry,
		&i.RawData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createIdentityProvider = `-- name: CreateIdentityProvider :one
INSERT INTO identity_providers (id, tenant_id, slug, name, protocol, client_id, client_secret_enc, issuer_url, authorization_url, token_url, userinfo_url, scopes, enabled, auto_register, config)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, tenant_id, slug, name, protocol, client_id, client_secret_enc, issuer_url, authorization_url, token_url, userinfo_url, scopes, enabled, auto_register, config, created_at, updated_at
`

type CreateIdentityProviderParams struct {
	ID               uuid.UUID   `db:"id" json:"id"`
	TenantID         pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	Slug             string      `db:"slug" json:"slug"`
	Name             string      `db:"name" json:"name"`
	Protocol         IdpProtocol `db:"protocol" json:"protocol"`
	ClientID         *string     `db:"client_id" json:"client_id"`
	ClientSecretEnc  *string     `db:"client_secret_enc" json:"client_secret_enc"`
	IssuerUrl        *string     `db:"issuer_url" json:"issuer_url"`
	AuthorizationUrl *string     `db:"authorization_url" json:"authorization_url"`
	TokenUrl         *string     `db:"token_url" json:"token_url"`
	UserinfoUrl      *string     `db:"userinfo_url" json:"userinfo_url"`
	Scopes           []string    `db:"scopes" json:"scopes"`
	Enabled          bool        `db:"enabled" json:"enabled"`
	AutoRegister     bool        `db:"auto_register" json:"auto_register"`
	Config           []byte      `db:"config" json:"config"`
}

func (q *Queries) CreateIdentityProvider(ctx context.Context, arg CreateIdentityProviderParams) (IdentityProvider, error) {
	row := q.db.QueryRow(ctx, createIdentityProvider,
		arg.ID,
		arg.TenantID,
		arg.Slug,
		arg.Name,
		arg.Protocol,
		arg.ClientID,
		arg.ClientSecretEnc,
		arg.IssuerUrl,
		arg.AuthorizationUrl,
		arg.TokenUrl,
		arg.UserinfoUrl,
		arg.Scopes,
		arg.Enabled,
		arg.AutoRegister,
		arg.Config,
	)
	var i IdentityProvider
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Protocol,
		&i.ClientID,
		&i.ClientSecretEnc,
		&i.IssuerUrl,
		&i.AuthorizationUrl,
		&i.TokenUrl,
		&i.UserinfoUrl,
		&i.Scopes,
		&i.Enabled,
		&i.AutoRegister,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExternalAccount = `-- name: DeleteExternalAccount :exec
DELETE FROM external_accounts WHERE id = $1
`

func (q *Queries) DeleteExternalAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteExternalAccount, id)
	return err
}

const getExternalAccountByProviderAndExternalID = `-- name: GetExternalAccountByProviderAndExternalID :one
SELECT id, user_id, provider_id, external_id, email, name, avatar_url, access_token, refresh_token, token_expiry, raw_data, created_at, updated_at FROM external_accounts
WHERE provider_id = $1 AND external_id = $2
`

type GetExternalAccountByProviderAndExternalIDParams struct {
	ProviderID uuid.UUID `db:"provider_id" json:"provider_id"`
	ExternalID string    `db:"external_id" json:"external_id"`
}

func (q *Queries) GetExternalAccountByProviderAndExternalID(ctx context.Context, arg GetExternalAccountByProviderAndExternalIDParams) (ExternalAccount, error) {
	row := q.db.QueryRow(ctx, getExternalAccountByProviderAndExternalID, arg.ProviderID, arg.ExternalID)
	var i ExternalAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProviderID,
		&i.ExternalID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiry,
		&i.RawData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExternalAccountsByUserID = `-- name: GetExternalAccountsByUserID :many
SELECT ea.id, ea.user_id, ea.provider_id, ea.external_id, ea.email, ea.name, ea.avatar_url, ea.access_token, ea.refresh_token, ea.token_expiry, ea.raw_data, ea.created_at, ea.updated_at, ip.name as provider_name, ip.protocol as provider_protocol
FROM external_accounts ea
JOIN identity_providers ip ON ea.provider_id = ip.id
WHERE ea.user_id = $1
`

type GetExternalAccountsByUserIDRow struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	UserID           uuid.UUID          `db:"user_id" json:"user_id"`
	ProviderID       uuid.UUID          `db:"provider_id" json:"provider_id"`
	ExternalID       string             `db:"external_id" json:"external_id"`
	Email            *string            `db:"email" json:"email"`
	Name             *string            `db:"name" json:"name"`
	AvatarUrl        *string            `db:"avatar_url" json:"avatar_url"`
	AccessToken      *string            `db:"access_token" json:"access_token"`
	RefreshToken     *string            `db:"refresh_token" json:"refresh_token"`
	TokenExpiry      pgtype.Timestamptz `db:"token_expiry" json:"token_expiry"`
	RawData          []byte             `db:"raw_data" json:"raw_data"`
	CreatedAt        time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt        time.Time          `db:"updated_at" json:"updated_at"`
	ProviderName     string             `db:"provider_name" json:"provider_name"`
	ProviderProtocol IdpProtocol        `db:"provider_protocol" json:"provider_protocol"`
}

func (q *Queries) GetExternalAccountsByUserID(ctx context.Context, userID uuid.UUID) ([]GetExternalAccountsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getExternalAccountsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetExternalAccountsByUserIDRow{}
	for rows.Next() {
		var i GetExternalAccountsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProviderID,
			&i.ExternalID,
			&i.Email,
			&i.Name,
			&i.AvatarUrl,
			&i.AccessToken,
			&i.RefreshToken,
			&i.TokenExpiry,
			&i.RawData,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProviderName,
			&i.ProviderProtocol,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIdentityProviderByID = `-- name: GetIdentityProviderByID :one
SELECT id, tenant_id, slug, name, protocol, client_id, client_secret_enc, issuer_url, authorization_url, token_url, userinfo_url, scopes, enabled, auto_register, config, created_at, updated_at FROM identity_providers
WHERE id = $1 AND enabled = true
`

func (q *Queries) GetIdentityProviderByID(ctx context.Context, id uuid.UUID) (IdentityProvider, error) {
	row := q.db.QueryRow(ctx, getIdentityProviderByID, id)
	var i IdentityProvider
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Protocol,
		&i.ClientID,
		&i.ClientSecretEnc,
		&i.IssuerUrl,
		&i.AuthorizationUrl,
		&i.TokenUrl,
		&i.UserinfoUrl,
		&i.Scopes,
		&i.Enabled,
		&i.AutoRegister,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdentityProviderByProtocol = `-- name: GetIdentityProviderByProtocol :one
SELECT id, tenant_id, slug, name, protocol, client_id, client_secret_enc, issuer_url, authorization_url, token_url, userinfo_url, scopes, enabled, auto_register, config, created_at, updated_at FROM identity_providers
WHERE protocol = $1 AND enabled = true
  AND (tenant_id = $2 OR $2::uuid IS NULL)
LIMIT 1
`

type GetIdentityProviderByProtocolParams struct {
	Protocol IdpProtocol `db:"protocol" json:"protocol"`
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) GetIdentityProviderByProtocol(ctx context.Context, arg GetIdentityProviderByProtocolParams) (IdentityProvider, error) {
	row := q.db.QueryRow(ctx, getIdentityProviderByProtocol, arg.Protocol, arg.TenantID)
	var i IdentityProvider
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Protocol,
		&i.ClientID,
		&i.ClientSecretEnc,
		&i.IssuerUrl,
		&i.AuthorizationUrl,
		&i.TokenUrl,
		&i.UserinfoUrl,
		&i.Scopes,
		&i.Enabled,
		&i.AutoRegister,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIdentityProviders = `-- name: ListIdentityProviders :many
SELECT id, tenant_id, slug, name, protocol, client_id, client_secret_enc, issuer_url, authorization_url, token_url, userinfo_url, scopes, enabled, auto_register, config, created_at, updated_at FROM identity_providers
WHERE (tenant_id = $1 OR $1::uuid IS NULL)
  AND enabled = true
ORDER BY name ASC
`

func (q *Queries) ListIdentityProviders(ctx context.Context, tenantID pgtype.UUID) ([]IdentityProvider, error) {
	rows, err := q.db.Query(ctx, listIdentityProviders, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityProvider{}
	for rows.Next() {
		var i IdentityProvider
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Slug,
			&i.Name,
			&i.Protocol,
			&i.ClientID,
			&i.ClientSecretEnc,
			&i.IssuerUrl,
			&i.AuthorizationUrl,
			&i.TokenUrl,
			&i.UserinfoUrl,
			&i.Scopes,
			&i.Enabled,
			&i.AutoRegister,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
