// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mfa.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const countRecoveryCodesForUser = `-- name: CountRecoveryCodesForUser :one
SELECT COUNT(*) FROM mfa_recovery_codes
WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) CountRecoveryCodesForUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRecoveryCodesForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMFAMethod = `-- name: CreateMFAMethod :one
INSERT INTO mfa_methods (user_id, type, name, secret_enc, verified, is_default)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, type, name, secret_enc, verified, is_default, created_at, last_used_at
`

type CreateMFAMethodParams struct {
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	Type      string    `db:"type" json:"type"`
	Name      *string   `db:"name" json:"name"`
	SecretEnc *string   `db:"secret_enc" json:"secret_enc"`
	Verified  bool      `db:"verified" json:"verified"`
	IsDefault bool      `db:"is_default" json:"is_default"`
}

func (q *Queries) CreateMFAMethod(ctx context.Context, arg CreateMFAMethodParams) (MfaMethod, error) {
	row := q.db.QueryRow(ctx, createMFAMethod,
		arg.UserID,
		arg.Type,
		arg.Name,
		arg.SecretEnc,
		arg.Verified,
		arg.IsDefault,
	)
	var i MfaMethod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.SecretEnc,
		&i.Verified,
		&i.IsDefault,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const createMFARecoveryCode = `-- name: CreateMFARecoveryCode :exec
INSERT INTO mfa_recovery_codes (user_id, code_hash)
VALUES ($1, $2)
`

type CreateMFARecoveryCodeParams struct {
	UserID   uuid.UUID `db:"user_id" json:"user_id"`
	CodeHash string    `db:"code_hash" json:"code_hash"`
}

func (q *Queries) CreateMFARecoveryCode(ctx context.Context, arg CreateMFARecoveryCodeParams) error {
	_, err := q.db.Exec(ctx, createMFARecoveryCode, arg.UserID, arg.CodeHash)
	return err
}

const deleteAllMFAMethodsForUser = `-- name: DeleteAllMFAMethodsForUser :exec
DELETE FROM mfa_methods WHERE user_id = $1
`

func (q *Queries) DeleteAllMFAMethodsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllMFAMethodsForUser, userID)
	return err
}

const deleteMFAMethod = `-- name: DeleteMFAMethod :exec
DELETE FROM mfa_methods WHERE id = $1 AND user_id = $2
`

type DeleteMFAMethodParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteMFAMethod(ctx context.Context, arg DeleteMFAMethodParams) error {
	_, err := q.db.Exec(ctx, deleteMFAMethod, arg.ID, arg.UserID)
	return err
}

const deleteRecoveryCodesForUser = `-- name: DeleteRecoveryCodesForUser :exec
DELETE FROM mfa_recovery_codes WHERE user_id = $1
`

func (q *Queries) DeleteRecoveryCodesForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRecoveryCodesForUser, userID)
	return err
}

const getMFAMethodByID = `-- name: GetMFAMethodByID :one
SELECT id, user_id, type, name, secret_enc, verified, is_default, created_at, last_used_at FROM mfa_methods WHERE id = $1 AND user_id = $2
`

type GetMFAMethodByIDParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetMFAMethodByID(ctx context.Context, arg GetMFAMethodByIDParams) (MfaMethod, error) {
	row := q.db.QueryRow(ctx, getMFAMethodByID, arg.ID, arg.UserID)
	var i MfaMethod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.SecretEnc,
		&i.Verified,
		&i.IsDefault,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getVerifiedTOTPForUser = `-- name: GetVerifiedTOTPForUser :one
SELECT id, user_id, type, name, secret_enc, verified, is_default, created_at, last_used_at FROM mfa_methods
WHERE user_id = $1 AND type = 'totp' AND verified = TRUE
LIMIT 1
`

func (q *Queries) GetVerifiedTOTPForUser(ctx context.Context, userID uuid.UUID) (MfaMethod, error) {
	row := q.db.QueryRow(ctx, getVerifiedTOTPForUser, userID)
	var i MfaMethod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.SecretEnc,
		&i.Verified,
		&i.IsDefault,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const hasVerifiedMFAForUser = `-- name: HasVerifiedMFAForUser :one
SELECT EXISTS(
    SELECT 1 FROM mfa_methods WHERE user_id = $1 AND verified = TRUE
) AS has_mfa
`

func (q *Queries) HasVerifiedMFAForUser(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasVerifiedMFAForUser, userID)
	var has_mfa bool
	err := row.Scan(&has_mfa)
	return has_mfa, err
}

const listMFAMethodsForUser = `-- name: ListMFAMethodsForUser :many
SELECT id, user_id, type, name, secret_enc, verified, is_default, created_at, last_used_at FROM mfa_methods WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListMFAMethodsForUser(ctx context.Context, userID uuid.UUID) ([]MfaMethod, error) {
	rows, err := q.db.Query(ctx, listMFAMethodsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MfaMethod{}
	for rows.Next() {
		var i MfaMethod
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Name,
			&i.SecretEnc,
			&i.Verified,
			&i.IsDefault,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnusedRecoveryCodes = `-- name: ListUnusedRecoveryCodes :many
SELECT id, user_id, code_hash, used_at, created_at FROM mfa_recovery_codes
WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) ListUnusedRecoveryCodes(ctx context.Context, userID uuid.UUID) ([]MfaRecoveryCode, error) {
	rows, err := q.db.Query(ctx, listUnusedRecoveryCodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MfaRecoveryCode{}
	for rows.Next() {
		var i MfaRecoveryCode
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CodeHash,
			&i.UsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMFAMethodVerified = `-- name: MarkMFAMethodVerified :one
UPDATE mfa_methods SET verified = TRUE
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, type, name, secret_enc, verified, is_default, created_at, last_used_at
`

type MarkMFAMethodVerifiedParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) MarkMFAMethodVerified(ctx context.Context, arg MarkMFAMethodVerifiedParams) (MfaMethod, error) {
	row := q.db.QueryRow(ctx, markMFAMethodVerified, arg.ID, arg.UserID)
	var i MfaMethod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Name,
		&i.SecretEnc,
		&i.Verified,
		&i.IsDefault,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const markRecoveryCodeUsed = `-- name: MarkRecoveryCodeUsed :exec
UPDATE mfa_recovery_codes SET used_at = NOW()
WHERE id = $1 AND user_id = $2 AND used_at IS NULL
`

type MarkRecoveryCodeUsedParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) MarkRecoveryCodeUsed(ctx context.Context, arg MarkRecoveryCodeUsedParams) error {
	_, err := q.db.Exec(ctx, markRecoveryCodeUsed, arg.ID, arg.UserID)
	return err
}
