// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql/driver"
	"fmt"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEventType string

const (
	AuditEventTypeUserregistered             AuditEventType = "user.registered"
	AuditEventTypeUserlogin                  AuditEventType = "user.login"
	AuditEventTypeUserlogout                 AuditEventType = "user.logout"
	AuditEventTypeUserpasswordChanged        AuditEventType = "user.password_changed"
	AuditEventTypeUserpasswordResetRequested AuditEventType = "user.password_reset_requested"
	AuditEventTypeUseremailVerified          AuditEventType = "user.email_verified"
	AuditEventTypeUserdisabled               AuditEventType = "user.disabled"
	AuditEventTypeUserdeleted                AuditEventType = "user.deleted"
	AuditEventTypeUserupdated                AuditEventType = "user.updated"
	AuditEventTypeSessioncreated             AuditEventType = "session.created"
	AuditEventTypeSessionrevoked             AuditEventType = "session.revoked"
	AuditEventTypeTokenrevoked               AuditEventType = "token.revoked"
	AuditEventTypeOidcClientcreated          AuditEventType = "oidc_client.created"
	AuditEventTypeOidcClientupdated          AuditEventType = "oidc_client.updated"
	AuditEventTypeOidcClientdeleted          AuditEventType = "oidc_client.deleted"
	AuditEventTypeIdpcreated                 AuditEventType = "idp.created"
	AuditEventTypeIdpupdated                 AuditEventType = "idp.updated"
)

func (e *AuditEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditEventType(s)
	case string:
		*e = AuditEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditEventType: %T", src)
	}
	return nil
}

type NullAuditEventType struct {
	AuditEventType AuditEventType `json:"audit_event_type"`
	Valid          bool           `json:"valid"` // Valid is true if AuditEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditEventType) Scan(value interface{}) error {
	if value == nil {
		ns.AuditEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditEventType), nil
}

type IdpProtocol string

const (
	IdpProtocolOidc   IdpProtocol = "oidc"
	IdpProtocolOauth2 IdpProtocol = "oauth2"
	IdpProtocolSaml   IdpProtocol = "saml"
	IdpProtocolLdap   IdpProtocol = "ldap"
	IdpProtocolScim   IdpProtocol = "scim"
)

func (e *IdpProtocol) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IdpProtocol(s)
	case string:
		*e = IdpProtocol(s)
	default:
		return fmt.Errorf("unsupported scan type for IdpProtocol: %T", src)
	}
	return nil
}

type NullIdpProtocol struct {
	IdpProtocol IdpProtocol `json:"idp_protocol"`
	Valid       bool        `json:"valid"` // Valid is true if IdpProtocol is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIdpProtocol) Scan(value interface{}) error {
	if value == nil {
		ns.IdpProtocol, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IdpProtocol.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIdpProtocol) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IdpProtocol), nil
}

type TokenType string

const (
	TokenTypePasswordReset      TokenType = "password_reset"
	TokenTypeEmailVerification  TokenType = "email_verification"
	TokenTypeInvite             TokenType = "invite"
	TokenTypeMagicLink          TokenType = "magic_link"
	TokenTypeMfa                TokenType = "mfa"
	TokenTypeDeviceVerification TokenType = "device_verification"
)

func (e *TokenType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TokenType(s)
	case string:
		*e = TokenType(s)
	default:
		return fmt.Errorf("unsupported scan type for TokenType: %T", src)
	}
	return nil
}

type NullTokenType struct {
	TokenType TokenType `json:"token_type"`
	Valid     bool      `json:"valid"` // Valid is true if TokenType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTokenType) Scan(value interface{}) error {
	if value == nil {
		ns.TokenType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TokenType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTokenType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TokenType), nil
}

type UserStatus string

const (
	UserStatusActive              UserStatus = "active"
	UserStatusDisabled            UserStatus = "disabled"
	UserStatusLocked              UserStatus = "locked"
	UserStatusPendingVerification UserStatus = "pending_verification"
	UserStatusInvited             UserStatus = "invited"
	UserStatusDeleted             UserStatus = "deleted"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type AuditLog struct {
	ID        uuid.UUID      `db:"id" json:"id"`
	TenantID  pgtype.UUID    `db:"tenant_id" json:"tenant_id"`
	ActorID   pgtype.UUID    `db:"actor_id" json:"actor_id"`
	TargetID  pgtype.UUID    `db:"target_id" json:"target_id"`
	Event     AuditEventType `db:"event" json:"event"`
	IpAddress *netip.Addr    `db:"ip_address" json:"ip_address"`
	UserAgent *string        `db:"user_agent" json:"user_agent"`
	Metadata  []byte         `db:"metadata" json:"metadata"`
	CreatedAt time.Time      `db:"created_at" json:"created_at"`
}

type AuthorizationCode struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	CodeHash   string             `db:"code_hash" json:"code_hash"`
	RequestID  uuid.UUID          `db:"request_id" json:"request_id"`
	ExpiresAt  time.Time          `db:"expires_at" json:"expires_at"`
	RedeemedAt pgtype.Timestamptz `db:"redeemed_at" json:"redeemed_at"`
	CreatedAt  time.Time          `db:"created_at" json:"created_at"`
}

type AuthorizationRequest struct {
	ID                  uuid.UUID   `db:"id" json:"id"`
	ClientID            string      `db:"client_id" json:"client_id"`
	UserID              pgtype.UUID `db:"user_id" json:"user_id"`
	Scopes              []string    `db:"scopes" json:"scopes"`
	RedirectUri         string      `db:"redirect_uri" json:"redirect_uri"`
	State               *string     `db:"state" json:"state"`
	Nonce               *string     `db:"nonce" json:"nonce"`
	CodeChallenge       *string     `db:"code_challenge" json:"code_challenge"`
	CodeChallengeMethod *string     `db:"code_challenge_method" json:"code_challenge_method"`
	ResponseType        string      `db:"response_type" json:"response_type"`
	Authenticated       bool        `db:"authenticated" json:"authenticated"`
	ExpiresAt           time.Time   `db:"expires_at" json:"expires_at"`
	CreatedAt           time.Time   `db:"created_at" json:"created_at"`
}

type Consent struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	ClientID  string             `db:"client_id" json:"client_id"`
	Scopes    []string           `db:"scopes" json:"scopes"`
	CreatedAt time.Time          `db:"created_at" json:"created_at"`
	RevokedAt pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

type DeviceCode struct {
	ID             uuid.UUID   `db:"id" json:"id"`
	ClientID       string      `db:"client_id" json:"client_id"`
	DeviceCodeHash string      `db:"device_code_hash" json:"device_code_hash"`
	UserCode       string      `db:"user_code" json:"user_code"`
	UserID         pgtype.UUID `db:"user_id" json:"user_id"`
	Scopes         []string    `db:"scopes" json:"scopes"`
	Verified       bool        `db:"verified" json:"verified"`
	ExpiresAt      time.Time   `db:"expires_at" json:"expires_at"`
	CreatedAt      time.Time   `db:"created_at" json:"created_at"`
}

type ExternalAccount struct {
	ID           uuid.UUID          `db:"id" json:"id"`
	UserID       uuid.UUID          `db:"user_id" json:"user_id"`
	ProviderID   uuid.UUID          `db:"provider_id" json:"provider_id"`
	ExternalID   string             `db:"external_id" json:"external_id"`
	Email        *string            `db:"email" json:"email"`
	Name         *string            `db:"name" json:"name"`
	AvatarUrl    *string            `db:"avatar_url" json:"avatar_url"`
	AccessToken  *string            `db:"access_token" json:"access_token"`
	RefreshToken *string            `db:"refresh_token" json:"refresh_token"`
	TokenExpiry  pgtype.Timestamptz `db:"token_expiry" json:"token_expiry"`
	RawData      []byte             `db:"raw_data" json:"raw_data"`
	CreatedAt    time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time          `db:"updated_at" json:"updated_at"`
}

type FeatureFlag struct {
	ID          uuid.UUID `db:"id" json:"id"`
	Key         string    `db:"key" json:"key"`
	Enabled     bool      `db:"enabled" json:"enabled"`
	Description *string   `db:"description" json:"description"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time `db:"updated_at" json:"updated_at"`
}

type IdentityProvider struct {
	ID               uuid.UUID   `db:"id" json:"id"`
	TenantID         pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	Slug             string      `db:"slug" json:"slug"`
	Name             string      `db:"name" json:"name"`
	Protocol         IdpProtocol `db:"protocol" json:"protocol"`
	ClientID         *string     `db:"client_id" json:"client_id"`
	ClientSecretEnc  *string     `db:"client_secret_enc" json:"client_secret_enc"`
	IssuerUrl        *string     `db:"issuer_url" json:"issuer_url"`
	AuthorizationUrl *string     `db:"authorization_url" json:"authorization_url"`
	TokenUrl         *string     `db:"token_url" json:"token_url"`
	UserinfoUrl      *string     `db:"userinfo_url" json:"userinfo_url"`
	Scopes           []string    `db:"scopes" json:"scopes"`
	Enabled          bool        `db:"enabled" json:"enabled"`
	AutoRegister     bool        `db:"auto_register" json:"auto_register"`
	Config           []byte      `db:"config" json:"config"`
	CreatedAt        time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt        time.Time   `db:"updated_at" json:"updated_at"`
}

type IdentityToken struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	Type      TokenType          `db:"type" json:"type"`
	Hash      string             `db:"hash" json:"hash"`
	ExpiresAt time.Time          `db:"expires_at" json:"expires_at"`
	UsedAt    pgtype.Timestamptz `db:"used_at" json:"used_at"`
	CreatedAt time.Time          `db:"created_at" json:"created_at"`
}

type MfaMethod struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	UserID     uuid.UUID          `db:"user_id" json:"user_id"`
	Type       string             `db:"type" json:"type"`
	Name       *string            `db:"name" json:"name"`
	SecretEnc  *string            `db:"secret_enc" json:"secret_enc"`
	Verified   bool               `db:"verified" json:"verified"`
	IsDefault  bool               `db:"is_default" json:"is_default"`
	CreatedAt  time.Time          `db:"created_at" json:"created_at"`
	LastUsedAt pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
}

type MfaRecoveryCode struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	UserID    uuid.UUID          `db:"user_id" json:"user_id"`
	CodeHash  string             `db:"code_hash" json:"code_hash"`
	UsedAt    pgtype.Timestamptz `db:"used_at" json:"used_at"`
	CreatedAt time.Time          `db:"created_at" json:"created_at"`
}

type OidcClient struct {
	ID                      string          `db:"id" json:"id"`
	TenantID                pgtype.UUID     `db:"tenant_id" json:"tenant_id"`
	ClientName              string          `db:"client_name" json:"client_name"`
	ClientSecretHash        *string         `db:"client_secret_hash" json:"client_secret_hash"`
	RedirectUris            []string        `db:"redirect_uris" json:"redirect_uris"`
	PostLogoutRedirectUris  []string        `db:"post_logout_redirect_uris" json:"post_logout_redirect_uris"`
	GrantTypes              []string        `db:"grant_types" json:"grant_types"`
	ResponseTypes           []string        `db:"response_types" json:"response_types"`
	Scopes                  []string        `db:"scopes" json:"scopes"`
	TokenEndpointAuthMethod string          `db:"token_endpoint_auth_method" json:"token_endpoint_auth_method"`
	PkceRequired            bool            `db:"pkce_required" json:"pkce_required"`
	ConsentRequired         bool            `db:"consent_required" json:"consent_required"`
	ApplicationType         string          `db:"application_type" json:"application_type"`
	JwksUri                 *string         `db:"jwks_uri" json:"jwks_uri"`
	Jwks                    []byte          `db:"jwks" json:"jwks"`
	LogoUri                 *string         `db:"logo_uri" json:"logo_uri"`
	TosUri                  *string         `db:"tos_uri" json:"tos_uri"`
	PolicyUri               *string         `db:"policy_uri" json:"policy_uri"`
	Contacts                []string        `db:"contacts" json:"contacts"`
	AccessTokenTtl          pgtype.Interval `db:"access_token_ttl" json:"access_token_ttl"`
	RefreshTokenTtl         pgtype.Interval `db:"refresh_token_ttl" json:"refresh_token_ttl"`
	IDTokenTtl              pgtype.Interval `db:"id_token_ttl" json:"id_token_ttl"`
	IsPublic                bool            `db:"is_public" json:"is_public"`
	Disabled                bool            `db:"disabled" json:"disabled"`
	CreatedAt               time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt               time.Time       `db:"updated_at" json:"updated_at"`
}

type Session struct {
	ID               uuid.UUID          `db:"id" json:"id"`
	UserID           uuid.UUID          `db:"user_id" json:"user_id"`
	TenantID         pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	RefreshTokenHash string             `db:"refresh_token_hash" json:"refresh_token_hash"`
	UserAgent        *string            `db:"user_agent" json:"user_agent"`
	IpAddress        *netip.Addr        `db:"ip_address" json:"ip_address"`
	ExpiresAt        time.Time          `db:"expires_at" json:"expires_at"`
	CreatedAt        time.Time          `db:"created_at" json:"created_at"`
	RevokedAt        pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

type TrustedDevice struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	UserID     uuid.UUID          `db:"user_id" json:"user_id"`
	DeviceHash string             `db:"device_hash" json:"device_hash"`
	Name       *string            `db:"name" json:"name"`
	LastUsedAt pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	ExpiresAt  time.Time          `db:"expires_at" json:"expires_at"`
	CreatedAt  time.Time          `db:"created_at" json:"created_at"`
}

type User struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	TenantID      pgtype.UUID        `db:"tenant_id" json:"tenant_id"`
	Email         string             `db:"email" json:"email"`
	Name          string             `db:"name" json:"name"`
	PasswordHash  *string            `db:"password_hash" json:"password_hash"`
	Status        UserStatus         `db:"status" json:"status"`
	EmailVerified bool               `db:"email_verified" json:"email_verified"`
	AvatarUrl     *string            `db:"avatar_url" json:"avatar_url"`
	CreatedAt     time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time          `db:"updated_at" json:"updated_at"`
	LastLoginAt   pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
	DeletedAt     pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}
