// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oidc_clients.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOIDCClient = `-- name: CreateOIDCClient :one
INSERT INTO oidc_clients (
    id, tenant_id, client_name, client_secret_hash,
    redirect_uris, post_logout_redirect_uris,
    response_types, grant_types, scopes,
    token_endpoint_auth_method, pkce_required,
    consent_required, application_type,
    access_token_ttl, refresh_token_ttl, id_token_ttl,
    is_public, disabled
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
RETURNING id, tenant_id, client_name, client_secret_hash, redirect_uris, post_logout_redirect_uris, grant_types, response_types, scopes, token_endpoint_auth_method, pkce_required, consent_required, application_type, jwks_uri, jwks, logo_uri, tos_uri, policy_uri, contacts, access_token_ttl, refresh_token_ttl, id_token_ttl, is_public, disabled, created_at, updated_at
`

type CreateOIDCClientParams struct {
	ID                      string          `db:"id" json:"id"`
	TenantID                pgtype.UUID     `db:"tenant_id" json:"tenant_id"`
	ClientName              string          `db:"client_name" json:"client_name"`
	ClientSecretHash        *string         `db:"client_secret_hash" json:"client_secret_hash"`
	RedirectUris            []string        `db:"redirect_uris" json:"redirect_uris"`
	PostLogoutRedirectUris  []string        `db:"post_logout_redirect_uris" json:"post_logout_redirect_uris"`
	ResponseTypes           []string        `db:"response_types" json:"response_types"`
	GrantTypes              []string        `db:"grant_types" json:"grant_types"`
	Scopes                  []string        `db:"scopes" json:"scopes"`
	TokenEndpointAuthMethod string          `db:"token_endpoint_auth_method" json:"token_endpoint_auth_method"`
	PkceRequired            bool            `db:"pkce_required" json:"pkce_required"`
	ConsentRequired         bool            `db:"consent_required" json:"consent_required"`
	ApplicationType         string          `db:"application_type" json:"application_type"`
	AccessTokenTtl          pgtype.Interval `db:"access_token_ttl" json:"access_token_ttl"`
	RefreshTokenTtl         pgtype.Interval `db:"refresh_token_ttl" json:"refresh_token_ttl"`
	IDTokenTtl              pgtype.Interval `db:"id_token_ttl" json:"id_token_ttl"`
	IsPublic                bool            `db:"is_public" json:"is_public"`
	Disabled                bool            `db:"disabled" json:"disabled"`
}

func (q *Queries) CreateOIDCClient(ctx context.Context, arg CreateOIDCClientParams) (OidcClient, error) {
	row := q.db.QueryRow(ctx, createOIDCClient,
		arg.ID,
		arg.TenantID,
		arg.ClientName,
		arg.ClientSecretHash,
		arg.RedirectUris,
		arg.PostLogoutRedirectUris,
		arg.ResponseTypes,
		arg.GrantTypes,
		arg.Scopes,
		arg.TokenEndpointAuthMethod,
		arg.PkceRequired,
		arg.ConsentRequired,
		arg.ApplicationType,
		arg.AccessTokenTtl,
		arg.RefreshTokenTtl,
		arg.IDTokenTtl,
		arg.IsPublic,
		arg.Disabled,
	)
	var i OidcClient
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientName,
		&i.ClientSecretHash,
		&i.RedirectUris,
		&i.PostLogoutRedirectUris,
		&i.GrantTypes,
		&i.ResponseTypes,
		&i.Scopes,
		&i.TokenEndpointAuthMethod,
		&i.PkceRequired,
		&i.ConsentRequired,
		&i.ApplicationType,
		&i.JwksUri,
		&i.Jwks,
		&i.LogoUri,
		&i.TosUri,
		&i.PolicyUri,
		&i.Contacts,
		&i.AccessTokenTtl,
		&i.RefreshTokenTtl,
		&i.IDTokenTtl,
		&i.IsPublic,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOIDCClient = `-- name: DeleteOIDCClient :exec
UPDATE oidc_clients SET disabled = true, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteOIDCClient(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteOIDCClient, id)
	return err
}

const getOIDCClientByID = `-- name: GetOIDCClientByID :one
SELECT id, tenant_id, client_name, client_secret_hash, redirect_uris, 
       post_logout_redirect_uris, response_types, grant_types,
       scopes, token_endpoint_auth_method, pkce_required,
       consent_required, application_type, jwks_uri, jwks,
       logo_uri, tos_uri, policy_uri, contacts,
       access_token_ttl, refresh_token_ttl, id_token_ttl,
       is_public, disabled, created_at, updated_at
FROM oidc_clients
WHERE id = $1 AND disabled = false
`

type GetOIDCClientByIDRow struct {
	ID                      string          `db:"id" json:"id"`
	TenantID                pgtype.UUID     `db:"tenant_id" json:"tenant_id"`
	ClientName              string          `db:"client_name" json:"client_name"`
	ClientSecretHash        *string         `db:"client_secret_hash" json:"client_secret_hash"`
	RedirectUris            []string        `db:"redirect_uris" json:"redirect_uris"`
	PostLogoutRedirectUris  []string        `db:"post_logout_redirect_uris" json:"post_logout_redirect_uris"`
	ResponseTypes           []string        `db:"response_types" json:"response_types"`
	GrantTypes              []string        `db:"grant_types" json:"grant_types"`
	Scopes                  []string        `db:"scopes" json:"scopes"`
	TokenEndpointAuthMethod string          `db:"token_endpoint_auth_method" json:"token_endpoint_auth_method"`
	PkceRequired            bool            `db:"pkce_required" json:"pkce_required"`
	ConsentRequired         bool            `db:"consent_required" json:"consent_required"`
	ApplicationType         string          `db:"application_type" json:"application_type"`
	JwksUri                 *string         `db:"jwks_uri" json:"jwks_uri"`
	Jwks                    []byte          `db:"jwks" json:"jwks"`
	LogoUri                 *string         `db:"logo_uri" json:"logo_uri"`
	TosUri                  *string         `db:"tos_uri" json:"tos_uri"`
	PolicyUri               *string         `db:"policy_uri" json:"policy_uri"`
	Contacts                []string        `db:"contacts" json:"contacts"`
	AccessTokenTtl          pgtype.Interval `db:"access_token_ttl" json:"access_token_ttl"`
	RefreshTokenTtl         pgtype.Interval `db:"refresh_token_ttl" json:"refresh_token_ttl"`
	IDTokenTtl              pgtype.Interval `db:"id_token_ttl" json:"id_token_ttl"`
	IsPublic                bool            `db:"is_public" json:"is_public"`
	Disabled                bool            `db:"disabled" json:"disabled"`
	CreatedAt               time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt               time.Time       `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetOIDCClientByID(ctx context.Context, id string) (GetOIDCClientByIDRow, error) {
	row := q.db.QueryRow(ctx, getOIDCClientByID, id)
	var i GetOIDCClientByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientName,
		&i.ClientSecretHash,
		&i.RedirectUris,
		&i.PostLogoutRedirectUris,
		&i.ResponseTypes,
		&i.GrantTypes,
		&i.Scopes,
		&i.TokenEndpointAuthMethod,
		&i.PkceRequired,
		&i.ConsentRequired,
		&i.ApplicationType,
		&i.JwksUri,
		&i.Jwks,
		&i.LogoUri,
		&i.TosUri,
		&i.PolicyUri,
		&i.Contacts,
		&i.AccessTokenTtl,
		&i.RefreshTokenTtl,
		&i.IDTokenTtl,
		&i.IsPublic,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOIDCClients = `-- name: ListOIDCClients :many
SELECT id, tenant_id, client_name, client_secret_hash, redirect_uris, post_logout_redirect_uris, grant_types, response_types, scopes, token_endpoint_auth_method, pkce_required, consent_required, application_type, jwks_uri, jwks, logo_uri, tos_uri, policy_uri, contacts, access_token_ttl, refresh_token_ttl, id_token_ttl, is_public, disabled, created_at, updated_at FROM oidc_clients
WHERE (tenant_id = $3 OR $3::uuid IS NULL)
  AND disabled = false
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListOIDCClientsParams struct {
	Limit    int32       `db:"limit" json:"limit"`
	Offset   int32       `db:"offset" json:"offset"`
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) ListOIDCClients(ctx context.Context, arg ListOIDCClientsParams) ([]OidcClient, error) {
	rows, err := q.db.Query(ctx, listOIDCClients, arg.Limit, arg.Offset, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OidcClient{}
	for rows.Next() {
		var i OidcClient
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ClientName,
			&i.ClientSecretHash,
			&i.RedirectUris,
			&i.PostLogoutRedirectUris,
			&i.GrantTypes,
			&i.ResponseTypes,
			&i.Scopes,
			&i.TokenEndpointAuthMethod,
			&i.PkceRequired,
			&i.ConsentRequired,
			&i.ApplicationType,
			&i.JwksUri,
			&i.Jwks,
			&i.LogoUri,
			&i.TosUri,
			&i.PolicyUri,
			&i.Contacts,
			&i.AccessTokenTtl,
			&i.RefreshTokenTtl,
			&i.IDTokenTtl,
			&i.IsPublic,
			&i.Disabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOIDCClient = `-- name: UpdateOIDCClient :one
UPDATE oidc_clients
SET client_name = COALESCE($2, client_name),
    redirect_uris = COALESCE($3, redirect_uris),
    post_logout_redirect_uris = COALESCE($4, post_logout_redirect_uris),
    disabled = COALESCE($5, disabled),
    updated_at = NOW()
WHERE id = $1
RETURNING id, tenant_id, client_name, client_secret_hash, redirect_uris, post_logout_redirect_uris, grant_types, response_types, scopes, token_endpoint_auth_method, pkce_required, consent_required, application_type, jwks_uri, jwks, logo_uri, tos_uri, policy_uri, contacts, access_token_ttl, refresh_token_ttl, id_token_ttl, is_public, disabled, created_at, updated_at
`

type UpdateOIDCClientParams struct {
	ID                     string   `db:"id" json:"id"`
	ClientName             *string  `db:"client_name" json:"client_name"`
	RedirectUris           []string `db:"redirect_uris" json:"redirect_uris"`
	PostLogoutRedirectUris []string `db:"post_logout_redirect_uris" json:"post_logout_redirect_uris"`
	Disabled               *bool    `db:"disabled" json:"disabled"`
}

func (q *Queries) UpdateOIDCClient(ctx context.Context, arg UpdateOIDCClientParams) (OidcClient, error) {
	row := q.db.QueryRow(ctx, updateOIDCClient,
		arg.ID,
		arg.ClientName,
		arg.RedirectUris,
		arg.PostLogoutRedirectUris,
		arg.Disabled,
	)
	var i OidcClient
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientName,
		&i.ClientSecretHash,
		&i.RedirectUris,
		&i.PostLogoutRedirectUris,
		&i.GrantTypes,
		&i.ResponseTypes,
		&i.Scopes,
		&i.TokenEndpointAuthMethod,
		&i.PkceRequired,
		&i.ConsentRequired,
		&i.ApplicationType,
		&i.JwksUri,
		&i.Jwks,
		&i.LogoUri,
		&i.TosUri,
		&i.PolicyUri,
		&i.Contacts,
		&i.AccessTokenTtl,
		&i.RefreshTokenTtl,
		&i.IDTokenTtl,
		&i.IsPublic,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
