// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptTenantInvitation = `-- name: AcceptTenantInvitation :one
UPDATE tenant_invitations
SET accepted_at = NOW()
WHERE id = $1 AND accepted_at IS NULL AND expires_at > NOW()
RETURNING id, tenant_id, email, role, token_hash, expires_at, accepted_at, created_at
`

func (q *Queries) AcceptTenantInvitation(ctx context.Context, id uuid.UUID) (TenantInvitation, error) {
	row := q.db.QueryRow(ctx, acceptTenantInvitation, id)
	var i TenantInvitation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const addTenantMember = `-- name: AddTenantMember :one
INSERT INTO tenant_members (
    tenant_id, user_id, role, joined_at
) VALUES (
    $1, $2, $3, NOW()
) RETURNING tenant_id, user_id, role, joined_at
`

type AddTenantMemberParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	UserID   uuid.UUID `db:"user_id" json:"user_id"`
	Role     string    `db:"role" json:"role"`
}

func (q *Queries) AddTenantMember(ctx context.Context, arg AddTenantMemberParams) (TenantMember, error) {
	row := q.db.QueryRow(ctx, addTenantMember, arg.TenantID, arg.UserID, arg.Role)
	var i TenantMember
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (
    name, slug, status, plan, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, NOW(), NOW()
) RETURNING id, name, slug, status, plan, created_at, updated_at
`

type CreateTenantParams struct {
	Name   string `db:"name" json:"name"`
	Slug   string `db:"slug" json:"slug"`
	Status string `db:"status" json:"status"`
	Plan   string `db:"plan" json:"plan"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.Name,
		arg.Slug,
		arg.Status,
		arg.Plan,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTenantInvitation = `-- name: CreateTenantInvitation :one
INSERT INTO tenant_invitations (
    tenant_id, email, role, token_hash, expires_at, created_at
) VALUES (
    $1, $2, $3, $4, $5, NOW()
) RETURNING id, tenant_id, email, role, token_hash, expires_at, accepted_at, created_at
`

type CreateTenantInvitationParams struct {
	TenantID  uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Email     string    `db:"email" json:"email"`
	Role      string    `db:"role" json:"role"`
	TokenHash string    `db:"token_hash" json:"token_hash"`
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateTenantInvitation(ctx context.Context, arg CreateTenantInvitationParams) (TenantInvitation, error) {
	row := q.db.QueryRow(ctx, createTenantInvitation,
		arg.TenantID,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i TenantInvitation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTenant = `-- name: DeleteTenant :exec
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) DeleteTenant(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTenant, id)
	return err
}

const deleteTenantInvitation = `-- name: DeleteTenantInvitation :exec
DELETE FROM tenant_invitations WHERE id = $1
`

func (q *Queries) DeleteTenantInvitation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTenantInvitation, id)
	return err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, slug, status, plan, created_at, updated_at FROM tenants WHERE id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, name, slug, status, plan, created_at, updated_at FROM tenants WHERE slug = $1
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantInvitationByID = `-- name: GetTenantInvitationByID :one
SELECT id, tenant_id, email, role, token_hash, expires_at, accepted_at, created_at FROM tenant_invitations WHERE id = $1
`

func (q *Queries) GetTenantInvitationByID(ctx context.Context, id uuid.UUID) (TenantInvitation, error) {
	row := q.db.QueryRow(ctx, getTenantInvitationByID, id)
	var i TenantInvitation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantInvitationByToken = `-- name: GetTenantInvitationByToken :one
SELECT id, tenant_id, email, role, token_hash, expires_at, accepted_at, created_at FROM tenant_invitations
WHERE token_hash = $1 AND accepted_at IS NULL AND expires_at > NOW()
`

func (q *Queries) GetTenantInvitationByToken(ctx context.Context, tokenHash string) (TenantInvitation, error) {
	row := q.db.QueryRow(ctx, getTenantInvitationByToken, tokenHash)
	var i TenantInvitation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantMember = `-- name: GetTenantMember :one
SELECT tenant_id, user_id, role, joined_at FROM tenant_members
WHERE tenant_id = $1 AND user_id = $2
`

type GetTenantMemberParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	UserID   uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetTenantMember(ctx context.Context, arg GetTenantMemberParams) (TenantMember, error) {
	row := q.db.QueryRow(ctx, getTenantMember, arg.TenantID, arg.UserID)
	var i TenantMember
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const listTenantInvitations = `-- name: ListTenantInvitations :many
SELECT id, tenant_id, email, role, token_hash, expires_at, accepted_at, created_at FROM tenant_invitations
WHERE tenant_id = $1 AND accepted_at IS NULL AND expires_at > NOW()
ORDER BY created_at DESC
`

func (q *Queries) ListTenantInvitations(ctx context.Context, tenantID uuid.UUID) ([]TenantInvitation, error) {
	rows, err := q.db.Query(ctx, listTenantInvitations, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantInvitation{}
	for rows.Next() {
		var i TenantInvitation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.Role,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantMembers = `-- name: ListTenantMembers :many
SELECT tm.tenant_id, tm.user_id, tm.role, tm.joined_at, u.email, u.name, u.avatar_url
FROM tenant_members tm
JOIN users u ON tm.user_id = u.id
WHERE tm.tenant_id = $1 AND u.deleted_at IS NULL
ORDER BY u.name ASC
`

type ListTenantMembersRow struct {
	TenantID  uuid.UUID `db:"tenant_id" json:"tenant_id"`
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	Role      string    `db:"role" json:"role"`
	JoinedAt  time.Time `db:"joined_at" json:"joined_at"`
	Email     string    `db:"email" json:"email"`
	Name      string    `db:"name" json:"name"`
	AvatarUrl *string   `db:"avatar_url" json:"avatar_url"`
}

func (q *Queries) ListTenantMembers(ctx context.Context, tenantID uuid.UUID) ([]ListTenantMembersRow, error) {
	rows, err := q.db.Query(ctx, listTenantMembers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantMembersRow{}
	for rows.Next() {
		var i ListTenantMembersRow
		if err := rows.Scan(
			&i.TenantID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.Email,
			&i.Name,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantsForUser = `-- name: ListTenantsForUser :many
SELECT t.id, t.name, t.slug, t.status, t.plan, t.created_at, t.updated_at, tm.role, tm.joined_at
FROM tenants t
JOIN tenant_members tm ON t.id = tm.tenant_id
WHERE tm.user_id = $1
ORDER BY t.name ASC
`

type ListTenantsForUserRow struct {
	ID        uuid.UUID `db:"id" json:"id"`
	Name      string    `db:"name" json:"name"`
	Slug      string    `db:"slug" json:"slug"`
	Status    string    `db:"status" json:"status"`
	Plan      string    `db:"plan" json:"plan"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
	Role      string    `db:"role" json:"role"`
	JoinedAt  time.Time `db:"joined_at" json:"joined_at"`
}

func (q *Queries) ListTenantsForUser(ctx context.Context, userID uuid.UUID) ([]ListTenantsForUserRow, error) {
	rows, err := q.db.Query(ctx, listTenantsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantsForUserRow{}
	for rows.Next() {
		var i ListTenantsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.Plan,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTenantMember = `-- name: RemoveTenantMember :exec
DELETE FROM tenant_members
WHERE tenant_id = $1 AND user_id = $2
`

type RemoveTenantMemberParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	UserID   uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) RemoveTenantMember(ctx context.Context, arg RemoveTenantMemberParams) error {
	_, err := q.db.Exec(ctx, removeTenantMember, arg.TenantID, arg.UserID)
	return err
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE tenants
SET name = $2,
    slug = $3,
    status = $4,
    plan = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, slug, status, plan, created_at, updated_at
`

type UpdateTenantParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	Name   string    `db:"name" json:"name"`
	Slug   string    `db:"slug" json:"slug"`
	Status string    `db:"status" json:"status"`
	Plan   string    `db:"plan" json:"plan"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenant,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Status,
		arg.Plan,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTenantMemberRole = `-- name: UpdateTenantMemberRole :one
UPDATE tenant_members
SET role = $3
WHERE tenant_id = $1 AND user_id = $2
RETURNING tenant_id, user_id, role, joined_at
`

type UpdateTenantMemberRoleParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	UserID   uuid.UUID `db:"user_id" json:"user_id"`
	Role     string    `db:"role" json:"role"`
}

func (q *Queries) UpdateTenantMemberRole(ctx context.Context, arg UpdateTenantMemberRoleParams) (TenantMember, error) {
	row := q.db.QueryRow(ctx, updateTenantMemberRole, arg.TenantID, arg.UserID, arg.Role)
	var i TenantMember
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const updateUserActiveTenant = `-- name: UpdateUserActiveTenant :one
UPDATE users
SET tenant_id = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, tenant_id, email, name, password_hash, status, email_verified, avatar_url, created_at, updated_at, last_login_at, deleted_at
`

type UpdateUserActiveTenantParams struct {
	ID       uuid.UUID   `db:"id" json:"id"`
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) UpdateUserActiveTenant(ctx context.Context, arg UpdateUserActiveTenantParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserActiveTenant, arg.ID, arg.TenantID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Status,
		&i.EmailVerified,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
	)
	return i, err
}
