// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
WHERE deleted_at IS NULL
  AND (tenant_id = $1 OR $1::uuid IS NULL)
`

func (q *Queries) CountUsers(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, password_hash, status, email_verified, avatar_url, tenant_id, metadata_public, metadata_private)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, email, name, password_hash, status, email_verified, avatar_url, created_at, updated_at, last_login_at, deleted_at, metadata_public, metadata_private
`

type CreateUserParams struct {
	Email           string      `db:"email" json:"email"`
	Name            string      `db:"name" json:"name"`
	PasswordHash    *string     `db:"password_hash" json:"password_hash"`
	Status          UserStatus  `db:"status" json:"status"`
	EmailVerified   bool        `db:"email_verified" json:"email_verified"`
	AvatarUrl       *string     `db:"avatar_url" json:"avatar_url"`
	TenantID        pgtype.UUID `db:"tenant_id" json:"tenant_id"`
	MetadataPublic  []byte      `db:"metadata_public" json:"metadata_public"`
	MetadataPrivate []byte      `db:"metadata_private" json:"metadata_private"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
		arg.Status,
		arg.EmailVerified,
		arg.AvatarUrl,
		arg.TenantID,
		arg.MetadataPublic,
		arg.MetadataPrivate,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Status,
		&i.EmailVerified,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.MetadataPublic,
		&i.MetadataPrivate,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, tenant_id, email, name, password_hash, status, email_verified, avatar_url, created_at, updated_at, last_login_at, deleted_at, metadata_public, metadata_private FROM users
WHERE email = $1
  AND deleted_at IS NULL
  AND (tenant_id = $2 OR (tenant_id IS NULL AND $2::uuid IS NULL))
`

type GetUserByEmailParams struct {
	Email    string      `db:"email" json:"email"`
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.Email, arg.TenantID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Status,
		&i.EmailVerified,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.MetadataPublic,
		&i.MetadataPrivate,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, tenant_id, email, name, password_hash, status, email_verified, avatar_url, created_at, updated_at, last_login_at, deleted_at, metadata_public, metadata_private FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Status,
		&i.EmailVerified,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.MetadataPublic,
		&i.MetadataPrivate,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, tenant_id, email, name, password_hash, status, email_verified, avatar_url, created_at, updated_at, last_login_at, deleted_at, metadata_public, metadata_private FROM users
WHERE deleted_at IS NULL
  AND (tenant_id = $3 OR $3::uuid IS NULL)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit    int32       `db:"limit" json:"limit"`
	Offset   int32       `db:"offset" json:"offset"`
	TenantID pgtype.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.Name,
			&i.PasswordHash,
			&i.Status,
			&i.EmailVerified,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
			&i.DeletedAt,
			&i.MetadataPublic,
			&i.MetadataPrivate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEmailVerified = `-- name: SetEmailVerified :exec
UPDATE users
SET email_verified = TRUE, status = 'active', updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SetEmailVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setEmailVerified, id)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET deleted_at = NOW(), status = 'deleted', updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = COALESCE($2, name),
    email = COALESCE($3, email),
    avatar_url = COALESCE($4, avatar_url),
    status = COALESCE($5, status),
    email_verified = COALESCE($6, email_verified),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, tenant_id, email, name, password_hash, status, email_verified, avatar_url, created_at, updated_at, last_login_at, deleted_at, metadata_public, metadata_private
`

type UpdateUserParams struct {
	ID            uuid.UUID   `db:"id" json:"id"`
	Name          *string     `db:"name" json:"name"`
	Email         *string     `db:"email" json:"email"`
	AvatarUrl     *string     `db:"avatar_url" json:"avatar_url"`
	Status        *UserStatus `db:"status" json:"status"`
	EmailVerified *bool       `db:"email_verified" json:"email_verified"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.AvatarUrl,
		arg.Status,
		arg.EmailVerified,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Status,
		&i.EmailVerified,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.MetadataPublic,
		&i.MetadataPrivate,
	)
	return i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}

const updateUserMetadata = `-- name: UpdateUserMetadata :one
UPDATE users
SET metadata_public = COALESCE($2, metadata_public),
    metadata_private = COALESCE($3, metadata_private),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, tenant_id, email, name, password_hash, status, email_verified, avatar_url, created_at, updated_at, last_login_at, deleted_at, metadata_public, metadata_private
`

type UpdateUserMetadataParams struct {
	ID              uuid.UUID `db:"id" json:"id"`
	MetadataPublic  []byte    `db:"metadata_public" json:"metadata_public"`
	MetadataPrivate []byte    `db:"metadata_private" json:"metadata_private"`
}

func (q *Queries) UpdateUserMetadata(ctx context.Context, arg UpdateUserMetadataParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserMetadata, arg.ID, arg.MetadataPublic, arg.MetadataPrivate)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.Status,
		&i.EmailVerified,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
		&i.MetadataPublic,
		&i.MetadataPrivate,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `db:"id" json:"id"`
	PasswordHash *string   `db:"password_hash" json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
