// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createWebhookDelivery = `-- name: CreateWebhookDelivery :one
INSERT INTO webhook_deliveries (
    subscription_id,
    event_id,
    event_type,
    status_code,
    error_message,
    success
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, subscription_id, event_id, event_type, status_code, error_message, success, attempted_at
`

type CreateWebhookDeliveryParams struct {
	SubscriptionID uuid.UUID `db:"subscription_id" json:"subscription_id"`
	EventID        uuid.UUID `db:"event_id" json:"event_id"`
	EventType      string    `db:"event_type" json:"event_type"`
	StatusCode     *int32    `db:"status_code" json:"status_code"`
	ErrorMessage   *string   `db:"error_message" json:"error_message"`
	Success        bool      `db:"success" json:"success"`
}

func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, createWebhookDelivery,
		arg.SubscriptionID,
		arg.EventID,
		arg.EventType,
		arg.StatusCode,
		arg.ErrorMessage,
		arg.Success,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.EventID,
		&i.EventType,
		&i.StatusCode,
		&i.ErrorMessage,
		&i.Success,
		&i.AttemptedAt,
	)
	return i, err
}

const createWebhookSubscription = `-- name: CreateWebhookSubscription :one
INSERT INTO webhook_subscriptions (
    tenant_id,
    url,
    secret,
    event_types,
    status
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, tenant_id, url, secret, event_types, status, created_at, updated_at, last_used_at
`

type CreateWebhookSubscriptionParams struct {
	TenantID   uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Url        string    `db:"url" json:"url"`
	Secret     *string   `db:"secret" json:"secret"`
	EventTypes []string  `db:"event_types" json:"event_types"`
	Status     string    `db:"status" json:"status"`
}

func (q *Queries) CreateWebhookSubscription(ctx context.Context, arg CreateWebhookSubscriptionParams) (WebhookSubscription, error) {
	row := q.db.QueryRow(ctx, createWebhookSubscription,
		arg.TenantID,
		arg.Url,
		arg.Secret,
		arg.EventTypes,
		arg.Status,
	)
	var i WebhookSubscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Url,
		&i.Secret,
		&i.EventTypes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteWebhookSubscription = `-- name: DeleteWebhookSubscription :exec
DELETE FROM webhook_subscriptions
WHERE id = $1 AND tenant_id = $2
`

type DeleteWebhookSubscriptionParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) DeleteWebhookSubscription(ctx context.Context, arg DeleteWebhookSubscriptionParams) error {
	_, err := q.db.Exec(ctx, deleteWebhookSubscription, arg.ID, arg.TenantID)
	return err
}

const getWebhookSubscriptionByID = `-- name: GetWebhookSubscriptionByID :one
SELECT id, tenant_id, url, secret, event_types, status, created_at, updated_at, last_used_at FROM webhook_subscriptions
WHERE id = $1 AND tenant_id = $2
`

type GetWebhookSubscriptionByIDParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) GetWebhookSubscriptionByID(ctx context.Context, arg GetWebhookSubscriptionByIDParams) (WebhookSubscription, error) {
	row := q.db.QueryRow(ctx, getWebhookSubscriptionByID, arg.ID, arg.TenantID)
	var i WebhookSubscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Url,
		&i.Secret,
		&i.EventTypes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listActiveWebhookSubscriptionsByTenant = `-- name: ListActiveWebhookSubscriptionsByTenant :many
SELECT id, tenant_id, url, secret, event_types, status, created_at, updated_at, last_used_at FROM webhook_subscriptions
WHERE tenant_id = $1 AND status = 'active'
ORDER BY created_at DESC
`

func (q *Queries) ListActiveWebhookSubscriptionsByTenant(ctx context.Context, tenantID uuid.UUID) ([]WebhookSubscription, error) {
	rows, err := q.db.Query(ctx, listActiveWebhookSubscriptionsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookSubscription{}
	for rows.Next() {
		var i WebhookSubscription
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Url,
			&i.Secret,
			&i.EventTypes,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFailedWebhookDeliveries = `-- name: ListFailedWebhookDeliveries :many
SELECT id, subscription_id, event_id, event_type, status_code, error_message, success, attempted_at FROM webhook_deliveries
WHERE success = false
ORDER BY attempted_at DESC
LIMIT 100
`

func (q *Queries) ListFailedWebhookDeliveries(ctx context.Context) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listFailedWebhookDeliveries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.EventID,
			&i.EventType,
			&i.StatusCode,
			&i.ErrorMessage,
			&i.Success,
			&i.AttemptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookSubscriptionsByTenant = `-- name: ListWebhookSubscriptionsByTenant :many
SELECT id, tenant_id, url, secret, event_types, status, created_at, updated_at, last_used_at FROM webhook_subscriptions
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWebhookSubscriptionsByTenant(ctx context.Context, tenantID uuid.UUID) ([]WebhookSubscription, error) {
	rows, err := q.db.Query(ctx, listWebhookSubscriptionsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookSubscription{}
	for rows.Next() {
		var i WebhookSubscription
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Url,
			&i.Secret,
			&i.EventTypes,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebhookSubscription = `-- name: UpdateWebhookSubscription :one
UPDATE webhook_subscriptions
SET url = $3,
    secret = $4,
    event_types = $5,
    status = $6,
    updated_at = NOW()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, url, secret, event_types, status, created_at, updated_at, last_used_at
`

type UpdateWebhookSubscriptionParams struct {
	ID         uuid.UUID `db:"id" json:"id"`
	TenantID   uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Url        string    `db:"url" json:"url"`
	Secret     *string   `db:"secret" json:"secret"`
	EventTypes []string  `db:"event_types" json:"event_types"`
	Status     string    `db:"status" json:"status"`
}

func (q *Queries) UpdateWebhookSubscription(ctx context.Context, arg UpdateWebhookSubscriptionParams) (WebhookSubscription, error) {
	row := q.db.QueryRow(ctx, updateWebhookSubscription,
		arg.ID,
		arg.TenantID,
		arg.Url,
		arg.Secret,
		arg.EventTypes,
		arg.Status,
	)
	var i WebhookSubscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Url,
		&i.Secret,
		&i.EventTypes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
	)
	return i, err
}
